name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
    # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
