name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
    # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your Github token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: slugb0t
          template: classic

          # Base content:
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_affiliations: owner, collaborator, organization_memeber

          # Timezone used by metrics
          config_timezone: America/Los_Angeles

          # Render display width
          config_display: large

          # Enable SVG CSS animations
          config_animations: yes

          # Number of retries in case rendering fails
          retries: 3

          # Time to wait (in seconds) before each retry
          retries_delay: 300

          # Ensure SVG can be correctly parsed after generation
          verify: yes

          # Most use languages
          plugin_languages: yes
          plugin_languages_color: github
          # Number of languages to display
          plugin_languages_limit: 7
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Lines of code changed
          plugin_lines: yes
          
